architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "figuraunchained.mixins.json"
    }
}

base {
    archivesName = "figura-unchained"
}
version = "${project.mod_version}+mc${project.forge_minecraft_label}+forge+figura${project.figura_version}"

dependencies {
    forge "net.minecraftforge:forge:${project.forge_version}"
    
    implementation project(path: ":common", configuration: "namedElements")
    
    modImplementation files("../libs/figura-${project.figura_version}+${project.minecraft_version}-forge-mc.jar")
}

processResources {
    from project(":common").sourceSets.main.resources
    
    inputs.property "version", project.version
    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Jar).configureEach {
    from project(":common").sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
